version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - export SPARROW_DOC_BUILD=1
    pre_install:
      - pip install --upgrade pip
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
sphinx:
  configuration: docs/conf.py
formats: []
