# File: .readthedocs.yaml

version: 2

# Specify the Python version and requirements file
python:
  install:
    - requirements: docs/requirements.txt

# Use the "readthedocs" environment to ensure all dependencies are installed before building
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

# Sphinx configuration
sphinx:
  configuration: docs/conf.py